
version: 2

models:
  - name: stg_amazon_sales_report_vw
    description: "Raw table View for changing few column names and datatypes"
    columns:
      - name: Row_ID
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

